### ISSUE TITLE
Remaining Productionization Tasks Checklist

### ISSUE THREAD

**Issue by aitrean** [MyCryptoHQ/typ3#20]
List of tasks that need to be finished before typ3 supports the full set of contract, filter, and node functionality. 

- [ ] #19 Overloading on the typ3 side (finished in the cli side)
- [ ] #4 Implement events using filters assigned to the connected contracts
- [x] #15 Clarify the code base with commenting, better organize typings and exports.
- [ ] #22 Support raw transaction creation for signing.
- [x] #18 Integrate TravisCI to the repo
- [x] Write docs
